import type { Langue } from '../demande'
import type { Forfait } from '../types'

// Textes de la page client et des fiches participants (français, anglais).

const FR = {
  forfaits: {
    classe_nature: 'Classe nature',
    journee_plein_air: 'Journée plein air',
    accueil_groupe: 'Accueil de groupe',
    location_salle: 'Location de salle',
  } as Record<Forfait, string>,
  chargement: 'Chargement…',
  lien_invalide: "Ce lien n'est pas valide.",
  lien_invalide_aide: "Vérifiez l'adresse reçue par courriel, ou écrivez-nous.",

  // Page client
  reservation: 'Réservation {n}',
  ferme: 'Ce dossier est fermé. Pour toute question, écrivez-nous.',
  sejour: 'Votre séjour',
  forfait: 'Forfait',
  dates: 'Dates',
  du_au: 'Du {a} au {d}',
  le: 'Le {a}',
  de_a: 'de {a} à {d}',
  participants: 'Participants',
  eleves_accompagnateurs: '{p} élèves et {a} accompagnateurs',
  personnes: '{p} personnes',
  estime: 'Votre estimé',
  estime_preparation: 'Votre estimé est en préparation : nous vous le ferons parvenir sous peu.',
  estime_version: 'Version {v} du {d}',
  description: 'Description',
  quantite: 'Qté',
  prix: 'Prix',
  montant: 'Montant',
  sous_total: 'Sous-total',
  tps: 'TPS (5 %)',
  tvq: 'TVQ (9,975 %)',
  total: 'Total',
  pdf: "Télécharger l'estimé (PDF)",
  accepter_case: "J'accepte cet estimé au nom du groupe.",
  votre_nom: 'Votre nom',
  accepter: "Accepter l'estimé",
  acceptation: 'Acceptation…',
  estime_accepte: '✓ Estimé accepté par {n} le {d}.',
  estime_accepte_court: '✓ Estimé accepté le {d}.',
  contrat: 'Votre contrat',
  contrat_a_venir: 'Votre contrat vous sera envoyé sous peu.',
  contrat_a_signer: 'Votre contrat est prêt : lisez-le et signez-le en ligne, au plus tard le {d}.',
  signer: 'Lire et signer le contrat',
  contrat_signe: '✓ Contrat signé par {n} le {d}. Votre réservation est confirmée.',
  documents: 'Vos documents',
  ouvrir: 'Ouvrir',
  genre_doc: { contrat_signe: 'Contrat signé', pre_arrivee: 'Informations avant l’arrivée' } as Record<string, string>,
  fiches: 'Fiches participants',
  fiches_aide:
    'Chaque élève et chaque adulte du groupe doit avoir sa fiche (allergies, diète, médicaments). Transmettez ce lien aux parents et aux accompagnateurs :',
  fiches_recues: '{r} fiche(s) reçue(s) sur {a} attendue(s).',
  copier: 'Copier le lien',
  copie: 'Copié ✓',
  question: 'Une question, un changement ?',
  question_aide: 'Écrivez-nous ici ; la personne responsable de votre dossier vous répondra.',
  message: 'Votre message',
  envoyer: 'Envoyer',
  envoi: 'Envoi…',
  message_envoye: 'Message envoyé. Nous vous répondrons sous peu.',

  // Fiches participants
  fiche_titre: 'Fiche participant',
  fiche_intro:
    'Remplissez une fiche pour chaque élève et chaque adulte (enseignant·e, accompagnateur·trice) qui participe au séjour. Ces renseignements servent à la sécurité et aux repas de chacun.',
  fiche_pour: 'Cette fiche est pour :',
  pour_participant: 'Un·e élève (participant·e)',
  pour_adulte: 'Un adulte (enseignant·e ou accompagnateur·trice)',
  prenom: 'Prénom',
  nom: 'Nom',
  groupe: 'Classe ou groupe',
  groupe_aide: 'Ex. : 5e année, groupe de Mme Tremblay. Facultatif.',
  matricule: 'Matricule',
  matricule_aide: 'Facultatif.',
  sante_enfant: 'Votre enfant a-t-il des allergies ou des problèmes de santé connus ?',
  sante_adulte: 'Avez-vous des allergies ou des problèmes de santé connus ?',
  allergies: 'Allergies',
  problemes: 'Problèmes de santé',
  sante_precisez: 'Précisez les allergies ou les problèmes de santé.',
  epipen_enfant: "Votre enfant a-t-il un auto-injecteur d'épinéphrine (Epipen) ?",
  epipen_adulte: "Avez-vous un auto-injecteur d'épinéphrine (Epipen) ?",
  diete_enfant: 'Diète de votre enfant',
  diete_adulte: 'Votre diète',
  dietes: {
    reguliere: 'Régulière (aucune restriction)',
    vegetarienne: 'Végétarienne',
    sans_porc: 'Sans porc',
    halal: 'Halal',
    sans_lactose: 'Sans lactose',
    sans_gluten: 'Sans gluten',
    autre: 'Autre',
  } as Record<string, string>,
  diete_autre: 'Précisez la diète',
  medicaments_enfant:
    'Si nécessaire, nous autorisez-vous à administrer à votre enfant les médicaments en vente libre que nous jugeons pertinents ?',
  medicaments_adulte: 'Si nécessaire, nous autorisez-vous à vous administrer les médicaments en vente libre que nous jugeons pertinents ?',
  oui: 'Oui',
  non: 'Non',
  courriel: 'Votre courriel',
  courriel_aide: 'Facultatif.',
  nouvelles: "J'accepte de recevoir des nouvelles de la Base de plein air Mont-Tremblant.",
  envoyer_fiche: 'Envoyer la fiche',
  fiche_recue: 'Merci ! La fiche de {n} est reçue.',
  autre_fiche: 'Remplir une autre fiche',
  fiches_fermees: 'Les fiches de ce séjour sont fermées.',
  obligatoire: 'Ce champ est obligatoire.',
  a_corriger: 'Quelques champs sont à compléter.',
  confidentialite:
    'Vos renseignements sont protégés (Loi 25) : seules les personnes responsables de la sécurité et des repas y ont accès, et ils sont effacés 3 mois après le séjour. Seul le courriel est gardé, si vous acceptez de recevoir nos nouvelles.',
}

type Textes = typeof FR

const EN: Textes = {
  forfaits: {
    classe_nature: 'Nature class',
    journee_plein_air: 'Outdoor day',
    accueil_groupe: 'Group reception',
    location_salle: 'Room rental',
  },
  chargement: 'Loading…',
  lien_invalide: 'This link is not valid.',
  lien_invalide_aide: 'Check the address you received by email, or write to us.',

  reservation: 'Reservation {n}',
  ferme: 'This file is closed. If you have any questions, please write to us.',
  sejour: 'Your stay',
  forfait: 'Package',
  dates: 'Dates',
  du_au: 'From {a} to {d}',
  le: 'On {a}',
  de_a: 'from {a} to {d}',
  participants: 'Participants',
  eleves_accompagnateurs: '{p} students and {a} chaperones',
  personnes: '{p} people',
  estime: 'Your estimate',
  estime_preparation: 'Your estimate is being prepared: we will send it to you shortly.',
  estime_version: 'Version {v}, {d}',
  description: 'Description',
  quantite: 'Qty',
  prix: 'Price',
  montant: 'Amount',
  sous_total: 'Subtotal',
  tps: 'GST (5%)',
  tvq: 'QST (9.975%)',
  total: 'Total',
  pdf: 'Download the estimate (PDF)',
  accepter_case: 'I accept this estimate on behalf of the group.',
  votre_nom: 'Your name',
  accepter: 'Accept the estimate',
  acceptation: 'Accepting…',
  estime_accepte: '✓ Estimate accepted by {n} on {d}.',
  estime_accepte_court: '✓ Estimate accepted on {d}.',
  contrat: 'Your contract',
  contrat_a_venir: 'Your contract will be sent to you shortly.',
  contrat_a_signer: 'Your contract is ready: read it and sign it online, no later than {d}.',
  signer: 'Read and sign the contract',
  contrat_signe: '✓ Contract signed by {n} on {d}. Your reservation is confirmed.',
  documents: 'Your documents',
  ouvrir: 'Open',
  genre_doc: { contrat_signe: 'Signed contract', pre_arrivee: 'Pre-arrival information' },
  fiches: 'Participant forms',
  fiches_aide: 'Each student and each adult in the group needs a form (allergies, diet, medication). Share this link with parents and chaperones:',
  fiches_recues: '{r} form(s) received out of {a} expected.',
  copier: 'Copy link',
  copie: 'Copied ✓',
  question: 'A question, a change?',
  question_aide: 'Write to us here; the person in charge of your file will get back to you.',
  message: 'Your message',
  envoyer: 'Send',
  envoi: 'Sending…',
  message_envoye: 'Message sent. We will get back to you shortly.',

  fiche_titre: 'Participant form',
  fiche_intro:
    'Fill out one form for each student and each adult (teacher, chaperone) taking part in the stay. This information is used for everyone’s safety and meals.',
  fiche_pour: 'This form is for:',
  pour_participant: 'A student (participant)',
  pour_adulte: 'An adult (teacher or chaperone)',
  prenom: 'First name',
  nom: 'Last name',
  groupe: 'Class or group',
  groupe_aide: 'E.g. Grade 5, Ms. Smith’s group. Optional.',
  matricule: 'Student number',
  matricule_aide: 'Optional.',
  sante_enfant: 'Does your child have any known allergies or health problems?',
  sante_adulte: 'Do you have any known allergies or health problems?',
  allergies: 'Allergies',
  problemes: 'Health problems',
  sante_precisez: 'Please specify the allergies or health problems.',
  epipen_enfant: 'Does your child have an epinephrine auto-injector (EpiPen)?',
  epipen_adulte: 'Do you have an epinephrine auto-injector (EpiPen)?',
  diete_enfant: "Your child's diet",
  diete_adulte: 'Your diet',
  dietes: {
    reguliere: 'Regular (no restrictions)',
    vegetarienne: 'Vegetarian',
    sans_porc: 'No pork',
    halal: 'Halal',
    sans_lactose: 'Lactose-free',
    sans_gluten: 'Gluten-free',
    autre: 'Other',
  },
  diete_autre: 'Please specify the diet',
  medicaments_enfant: 'If necessary, do you authorize us to give your child the over-the-counter medication we deem appropriate?',
  medicaments_adulte: 'If necessary, do you authorize us to give you the over-the-counter medication we deem appropriate?',
  oui: 'Yes',
  non: 'No',
  courriel: 'Your email',
  courriel_aide: 'Optional.',
  nouvelles: 'I agree to receive news from Base de plein air Mont-Tremblant.',
  envoyer_fiche: 'Send the form',
  fiche_recue: 'Thank you! The form for {n} has been received.',
  autre_fiche: 'Fill out another form',
  fiches_fermees: 'The forms for this stay are closed.',
  obligatoire: 'This field is required.',
  a_corriger: 'Some fields need to be completed.',
  confidentialite:
    'Your information is protected (Quebec Law 25): only the people responsible for safety and meals can see it, and it is deleted 3 months after the stay. Only your email is kept, if you agree to receive our news.',
}

export const TEXTES_PUBLICS: Record<Langue, Textes> = { fr: FR, en: EN }
